apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: automatic-system
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api-gateway
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 768Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: api-gateway
