-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),external_id text UNIQUE,department_id uuid NOT NULL,type text NOT NULL,name text NOT NULL,address text NOT NULL DEFAULT '',district text NOT NULL DEFAULT '',municipality text NOT NULL DEFAULT '',geometry geometry(Geometry,4326) NOT NULL,status text NOT NULL DEFAULT 'ACTIVE',model text NOT NULL DEFAULT '',serial_number text NOT NULL DEFAULT '',installation_year int,service_life_years int,warranty_until timestamptz,owner text NOT NULL DEFAULT '',service_organization text NOT NULL DEFAULT '',contractor text NOT NULL DEFAULT '',inspection_interval_days int NOT NULL DEFAULT 365,response_norm_minutes int NOT NULL DEFAULT 60,repair_norm_minutes int NOT NULL DEFAULT 1440,criticality double precision NOT NULL DEFAULT .5,risk_score double precision NOT NULL DEFAULT 0,risk_level text NOT NULL DEFAULT 'LOW',last_repair_at timestamptz,next_inspection_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX assets_geometry_idx ON assets USING gist(geometry);CREATE INDEX assets_filter_idx ON assets(department_id,type,status,risk_level);
CREATE TABLE asset_status_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,old_status text,new_status text NOT NULL,reason text NOT NULL,changed_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE asset_incidents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,ticket_id uuid,failure_type text NOT NULL,description text NOT NULL,source text NOT NULL,priority text NOT NULL,repeated bool NOT NULL DEFAULT false,occurred_at timestamptz NOT NULL);
CREATE TABLE asset_repairs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,incident_id uuid,ticket_id uuid,brigade_id uuid,description text NOT NULL,replaced_components text NOT NULL,duration_minutes int NOT NULL,completed_at timestamptz NOT NULL);
CREATE TABLE asset_inspections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,inspector_user_id uuid NOT NULL,kind text NOT NULL,result text NOT NULL,defect_found bool NOT NULL,condition_score double precision NOT NULL,recommendation text NOT NULL,inspected_at timestamptz NOT NULL);
CREATE TABLE maintenance_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,kind text NOT NULL,interval_days int NOT NULL,next_due_at timestamptz NOT NULL,active bool NOT NULL DEFAULT true,last_completed_at timestamptz,UNIQUE(asset_id,kind));
CREATE TABLE failure_predictions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),asset_id uuid NOT NULL REFERENCES assets,risk_score double precision NOT NULL,risk_level text NOT NULL,failure_probability_90d double precision NOT NULL,factors jsonb NOT NULL,recommended_action text NOT NULL,calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),aggregate_id uuid NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'PENDING',attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),locked_at timestamptz,sent_at timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now());
-- +goose Down
DROP TABLE outbox_events,failure_predictions,maintenance_plans,asset_inspections,asset_repairs,asset_incidents,asset_status_history,assets;
