{
 "title": "Community / ClickHouse Official",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ClickHouse Cloud Service Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(up{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "ClickHouse Cloud Service ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(up{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ClickHouse Cloud Org ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(up{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{clickhouse_org}}"
    }
   ]
  },
  {
   "title": "ClickHouse Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(up{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{clickhouse_version}}"
    }
   ]
  },
  {
   "title": "Service Status History",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(up{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of databases",
   "type": "stat",
   "description": "Number of databases per service. Includes system databases.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(max(ClickHouseAsyncMetrics_NumberOfDatabases{job=\"clickhouse\"})) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of tables",
   "type": "stat",
   "description": "Number of tables per service. Includes system tables.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(max(ClickHouseAsyncMetrics_NumberOfTables{job=\"clickhouse\"})) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total data in MergeTree tables",
   "type": "stat",
   "description": "Compressed. Includes system tables.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by () (ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTables{job=\"clickhouse\"})) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data selected per second",
   "type": "stat",
   "description": "Uncompressed, as stored in memory.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(ClickHouseProfileEvents_SelectedBytes{job=\"clickhouse\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data inserted per second",
   "type": "stat",
   "description": "Uncompressed, as stored in memory.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{job=\"clickhouse\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Max Server CPU Usage",
   "type": "stat",
   "description": "Maximum CPU usage among the server pods over the specified period of time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "((ClickHouseAsyncMetrics_CGroupUserTimeNormalized{\n    job=\"clickhouse\",\n}\n+\nClickHouseAsyncMetrics_CGroupSystemTimeNormalized{\n    job=\"clickhouse\",\n}) * 100) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Server Memory Usage",
   "type": "stat",
   "description": "Maximum server memory usage among the server pods over the specified period of time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_MemoryTracking{\n    job=\"clickhouse\",\n}\n/\nignoring(table)\nClickHouseAsyncMetrics_CGroupMemoryTotal{\n    job=\"clickhouse\",\n} * 100) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Parts Per Partition",
   "type": "stat",
   "description": "Maximum number of parts per partition over the specified period of time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(max(ClickHouseAsyncMetrics_MaxPartCountForPartition{job=\"clickhouse\"})) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Percent of Failed SELECTs",
   "type": "stat",
   "description": "Maximum percentage of the failed SELECTs over the specified period of time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_FailedSelectQuery{job=\"clickhouse\"}[$__rate_interval]) / rate(ClickHouseProfileEvents_SelectQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Percent of Failed INSERTs",
   "type": "stat",
   "description": "Maximum percentage of the failed INSERTs over the specified period of time (both synchronous and asynchronous).",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "((\n    rate(ClickHouseProfileEvents_FailedInsertQuery{job=\"clickhouse\"}[$__rate_interval]) \n    + \n    rate(ClickHouseProfileEvents_FailedAsyncInsertQuery{job=\"clickhouse\"}[$__rate_interval])\n)\n/\n(\n    rate(ClickHouseProfileEvents_AsyncInsertQuery{job=\"clickhouse\"}[$__rate_interval])\n    +\n    rate(ClickHouseProfileEvents_InsertQuery{job=\"clickhouse\"}[$__rate_interval])\n)) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max logged errors",
   "type": "stat",
   "description": "Maximum number of log message with ERROR (and higher) severity over the specified period of time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_LogError{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Cores Used by Queries/Merges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds{job=\"clickhouse\"}[$__rate_interval]) / 1000000) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Normalized CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(ClickHouseAsyncMetrics_CGroupUserTimeNormalized{job=\"clickhouse\"} + ClickHouseAsyncMetrics_CGroupSystemTimeNormalized{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_MemoryTracking{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Connections (TCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_TCPConnection{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_NetworkReceiveBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}} received"
    },
    {
     "expr": "(rate(ClickHouseProfileEvents_NetworkSendBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}} sent"
    }
   ]
  },
  { "title": "Queries Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Total Queries",
   "type": "timeseries",
   "description": "Number of queries to be interpreted and potentially executed. Does not include asynchronous inserts. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_Query{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query latency (average)",
   "type": "timeseries",
   "description": "Average query latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_QueryTimeMicroseconds{job=\"clickhouse\"}[$__rate_interval])  / increase(ClickHouseProfileEvents_Query{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries with MEMORY_LIMIT_EXCEEDED",
   "type": "timeseries",
   "description": "Number of times when memory limit exceeded for query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "description": "Number of failed queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_FailedQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT Queries",
   "type": "timeseries",
   "description": "Same as Queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synchronous INSERT Queries",
   "type": "timeseries",
   "description": "Same as Queries, but only for INSERT queries. Only accounts for synchronous inserts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_InsertQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed SELECT Queries",
   "type": "timeseries",
   "description": "Same as Failed Queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_FailedSelectQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Synchronous INSERT Queries",
   "type": "timeseries",
   "description": "Same as Failed Queries, but only for INSERT queries. Only accounts for Synchronous inserts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_FailedInsertQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT query latency (average)",
   "type": "timeseries",
   "description": "Average SELECT query latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{job=\"clickhouse\"}[$__rate_interval])  / increase(ClickHouseProfileEvents_SelectQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synchronous INSERT query latency (average)",
   "type": "timeseries",
   "description": "Average INSERT query latency. Accounts only for synchronous inserts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{job=\"clickhouse\"}[$__rate_interval])  / increase(ClickHouseProfileEvents_InsertQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Asynchronous INSERT Queries",
   "type": "timeseries",
   "description": "Same as Queries, but only for INSERT queries. Only accounts for asynchronous inserts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_AsyncInsertQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Asynchronous INSERT Queries",
   "type": "timeseries",
   "description": "Same as Failed Queries, but only for INSERT queries. Only accounts for asynchronous inserts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_FailedAsyncInsertQuery{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Asynchronous INSERT queries",
   "type": "timeseries",
   "description": "Number of asynchronous inserts waiting to be flushed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_PendingAsyncInsert{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Select Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Selected Parts",
   "type": "timeseries",
   "description": "Number of data parts selected to read.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectedParts{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Ranges",
   "type": "timeseries",
   "description": "Number of (non-adjacent) ranges in all data parts selected to read.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectedRanges{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Marks",
   "type": "timeseries",
   "description": "Number of index granules (marks) selected to read.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectedMarks{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Rows",
   "type": "timeseries",
   "description": "Number of rows selected from all tables (including system tables).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectedRows{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Bytes",
   "type": "timeseries",
   "description": "Bytes selected from all tables (uncompressed, for columns as they stored in memory, including system tables)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_SelectedRows{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Insert Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "Inserted rows (all tables)",
   "type": "timeseries",
   "description": "Number of rows inserted to all tables (including system tables).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_InsertedRows{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inserted bytes (all tables)",
   "type": "timeseries",
   "description": "Bytes inserted to all tables (uncompressed, for all columns as they are stored in memory, including system tables)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_InsertedBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree inserted rows",
   "type": "timeseries",
   "description": "Number of rows INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergeTreeDataWriterRows{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree inserted blocks",
   "type": "timeseries",
   "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree uncompressed bytes",
   "type": "timeseries",
   "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MergeTree compressed bytes",
   "type": "timeseries",
   "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Inserts (TOO_MANY_PARTS)",
   "type": "timeseries",
   "description": "Rate of rejected inserts due to \"TOO_MANY_PARTS\" exception.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_RejectedInserts{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delayed Inserts",
   "type": "timeseries",
   "description": "Rate inserts that were throttled due to high number of active data parts for partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_DelayedInserts{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delayed Inserts Latency (average)",
   "type": "timeseries",
   "description": "Average time that insert was throttled due to high number of active data parts for partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_DelayedInsertsMilliseconds{job=\"clickhouse\"}[$__rate_interval])  / increase(ClickHouseProfileEvents_DelayedInserts{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Merges Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 } },
  {
   "title": "Merges",
   "type": "timeseries",
   "description": "Number of launched background merges.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_Merge{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "timeseries",
   "description": "Number of running mutations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_PartMutation{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used by mutations & merges",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated by background tasks (merges and mutations).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_MergesMutationsMemoryTracking{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merge duration (average)",
   "type": "timeseries",
   "description": "Average merge duration (milliseconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(increase(ClickHouseProfileEvents_MergeTotalMilliseconds{job=\"clickhouse\"}[$__rate_interval])  / increase(ClickHouseProfileEvents_Merge{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged rows",
   "type": "timeseries",
   "description": "Rows read for background merges. This is the number of rows before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergedRows{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merged bytes (uncompressed)",
   "type": "timeseries",
   "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(ClickHouseProfileEvents_MergedUncompressedBytes{job=\"clickhouse\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Space reserved for merges",
   "type": "timeseries",
   "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_DiskSpaceReservedForMerge{job=\"clickhouse\"}) or vector(0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local instance cache size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_FilesystemCacheSize{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Local instance cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(rate(ClickHouseProfileEvents_CachedReadBufferReadFromCacheBytes{job=\"clickhouse\"}[$__rate_interval])\n/\n(rate(ClickHouseProfileEvents_CachedReadBufferReadFromCacheBytes{job=\"clickhouse\"}[$__rate_interval])\n+\nrate(ClickHouseProfileEvents_CachedReadBufferReadFromSourceBytes{job=\"clickhouse\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Local instance page cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(rate(ClickHouseProfileEvents_OSReadChars{job=\"clickhouse\"}[$__rate_interval])\n/\n(rate(ClickHouseProfileEvents_OSReadChars{job=\"clickhouse\"}[$__rate_interval])\n+\nrate(ClickHouseProfileEvents_ReadBufferFromS3Bytes{job=\"clickhouse\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mark cache hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(rate(ClickHouseProfileEvents_MarkCacheHits{job=\"clickhouse\"}[$__rate_interval])\n/\n(rate(ClickHouseProfileEvents_MarkCacheHits{job=\"clickhouse\"}[$__rate_interval])\n+\nrate(ClickHouseProfileEvents_MarkCacheMisses{job=\"clickhouse\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parts Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total parts",
     "type": "timeseries",
     "description": "Total amount of data parts in all tables of MergeTree family. Numbers larger than 10 000 will negatively affect the server startup time, and it may indicate unreasonable choice of the partition key.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "targets": [
      {
       "expr": "(max(ClickHouseAsyncMetrics_TotalPartsOfMergeTreeTables{job=\"clickhouse\"})) or vector(0)",
       "legendFormat": "Total parts"
      }
     ]
    },
    {
     "title": "Pre-active parts",
     "type": "timeseries",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsPreActive{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Temporary parts",
     "type": "timeseries",
     "description": "The part is being generating now, it is not in data_parts list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsTemporary{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outdated parts",
     "type": "timeseries",
     "description": "Data part that could be used only running SELECTs. Could be deleted after queries finish.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsOutdated{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active parts",
     "type": "timeseries",
     "description": "Active data parts, used by SELECTs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsActive{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compact parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsCompact{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Parts being deleted",
     "type": "timeseries",
     "description": "Parts in a \"Deleting\" status. Not an active data part with identity refcounter, it is  being deleted right now by a cleaner.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsDeleting{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Wide parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ClickHouseMetrics_PartsWide{job=\"clickhouse\"}) or vector(0)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}