{
 "title": "Community / Kubernetes Overview",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. Forked and modified version of: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   { "name": "job", "query": "node-exporter" },
   { "name": "lookbackPeriod", "label": "Max Capacity Lookback Period", "query": "1h, 4h, 8h, 12h, 24h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\"}) / sum(machine_cpu_cores{job=~\".+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node!=\"\"}) / sum(machine_cpu_cores{job=~\".+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\"}) / sum(machine_memory_bytes{job=~\".+\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", node!=\"\"}) / sum(machine_memory_bytes{job=~\".+\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{job=~\".+\"}))"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{job=~\".+\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=\"node-exporter\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node!=\"\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{job=~\".+\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory GiB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})  / 1024 / 1024 / 1024",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})  / 1024 / 1024 / 1024",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{job=~\".+\"})  / 1024 / 1024 / 1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Linux"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Node Efficiency",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\"}) by (node) / sum(kube_node_status_allocatable{resource=\"cpu\",job=~\".+\"}) by (node)"
    },
    {
     "expr": "max(\n  sum by (cpu, node) (\n    label_replace(\n      max(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=\"node-exporter\"}[1d]))) by (instance),\n      \"node\",\n      \"$1\",\n      \"instance\",\n      \"(.*):\\\\d+\"\n    )\n  )\n) by (node)\n"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\"}) by (node) / sum(kube_node_status_allocatable{resource=\"memory\",job=~\".+\"}) by (node)"
    },
    {
     "expr": "    sum(\n      label_replace(\n        (1 - \n        (node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"})\n        ) * 100, \"node\",\n      \"$1\",\n      \"instance\",\n      \"(.*):\\\\d+\"\n    ))  by (node)"
    },
    {
     "expr": "count(kube_pod_info{host_network=\"false\",job=~\".+\"}) by (node) / sum(kube_node_status_allocatable{resource=\"pods\",job=~\".+\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overprovisioned Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overprovisioned CPU millicores",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "max_over_time(sum(rate(container_cpu_usage_seconds_total{container!=\"\",job=~\".+\"}[10m])) by (namespace, pod, container)[$lookbackPeriod:10m]) * 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\",node!=\"\",job=~\".+\"}) by (namespace, pod, container) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Overprovisioned Memory",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max_over_time(sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace, pod, container)[$lookbackPeriod:10m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",node!=\"\",job=~\".+\"}) by (namespace, pod, container)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=\"node-exporter\"}[$__rate_interval]))) by (instance)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Memory Utilization by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    { "title": "CPU Utilization by namespace", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 }, "fieldConfig": { "defaults": { "unit": "none" } } },
    {
     "title": "Memory Utilization by namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } }
    },
    {
     "title": "CPU Throttled seconds by namespace",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace) > 0",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "CPU Core Throttled by instance",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } }
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Resource Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{job=~\".+\"})",
       "legendFormat": "Running Containers"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_info{job=~\".+\"})",
       "legendFormat": "Persistent Volume Claims"
      },
      {
       "expr": "count(count by (node) (kube_node_info{job=~\".+\"}))",
       "legendFormat": "Nodes"
      }
     ]
    },
    {
     "title": "Kubernetes Pods QoS classes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_qos_class{job=~\".+\"}) by (qos_class)",
       "legendFormat": "{{ qos_class }} pods"
      },
      {
       "expr": "sum(kube_pod_info{job=~\".+\"})",
       "legendFormat": "Total pods"
      }
     ]
    },
    {
     "title": "Kubernetes Pods Status Reason",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_reason{job=~\".+\"}) by (reason)",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "OOM Events by namespace",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum(increase(container_oom_events_total{job=~\".+\"}[$__rate_interval])) by (namespace) > 0) or vector(0)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Container Restarts by namespace",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum(increase(kube_pod_container_status_restarts_total{job=~\".+\"}[$__rate_interval])) by (namespace) > 0) or vector(0)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Network Utilization by device",
     "type": "timeseries",
     "description": "Dropped noisy virtual devices for readability.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 448 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\", job=\"node-exporter\"}[$__rate_interval])) by (device)",
       "legendFormat": "Received : {{ device }}"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\", job=\"node-exporter\"}[$__rate_interval])) by (device)",
       "legendFormat": "Transmitted : {{ device }}"
      }
     ]
    },
    {
     "title": "Network Saturation - Packets dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 448 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_drop_total{job=\"node-exporter\"}[$__rate_interval]))",
       "legendFormat": "Linux Packets dropped (receive)"
      },
      {
       "expr": "- sum(rate(node_network_transmit_drop_total{job=\"node-exporter\"}[$__rate_interval]))",
       "legendFormat": "Linux Packets dropped (transmit)"
      }
     ]
    },
    { "title": "Network Received by namespace", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 456 }, "fieldConfig": { "defaults": { "unit": "binBps" } } },
    {
     "title": "Total Network Received (with all virtual devices) by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Received bytes in {{ instance }}"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Transmitted bytes in {{ instance }}"
      }
     ]
    },
    {
     "title": "Network Received (without loopback)  by instance",
     "type": "timeseries",
     "description": "Dropped noisy virtual devices for readability.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 464 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\", job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Received bytes in {{ instance }}"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\", job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Transmitted bytes in {{ instance }}"
      }
     ]
    },
    {
     "title": "Network Received (loopback only) by instance",
     "type": "timeseries",
     "description": "Dropped noisy virtual devices for readability.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 464 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\", job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Received bytes in {{ instance }}"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\", job=\"node-exporter\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Transmitted bytes in {{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}