{
 "title": "Community / PostgreSQL Patroni",
 "description": "Patroni dashboard for use with Percona Monitoring and Management version 2.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "scope_name",
    "label": "Scope Name",
    "query": {
     "query": "label_values(patroni_version{job=\"patroni\"}, scope)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$service_name</span> with <span style='color:#e68a00'>$interval</span> resolution</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Patroni Version",
   "type": "stat",
   "description": "Reports Patroni version number.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_version{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{job=\"patroni\",scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "Patroni Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_primary{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Replica",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_replica{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Standby Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_standby_leader{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Autofailover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_is_paused{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Reports Patroni version number.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_server_version{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postmaster_start_time{job=\"patroni\",scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "PostgreSQL Running (Timeline)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_running{job=\"patroni\",scope=~\"$scope_name\"}"
    },
    {
     "expr": "patroni_postgres_timeline{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Pending Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_pending_restart{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Replay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_xlog_paused{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Sync Standby",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_sync_standby{job=\"patroni\",scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Patroni Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_primary{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Patroni Secondary Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_replica{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL Replay Paused",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_paused{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Primary WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_location{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replicas Received WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_received_location{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replicas Replayed WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_replayed_location{job=\"patroni\",scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}