apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  GRPC_PORT: '50051'
  DB_HOST: postgres-auth
  DB_PORT: '5432'
  DB_USERNAME: auth_user
  DB_NAME: auth_db
  SSLMODE: disable
  JWT_PRIVATE_KEY_PATH: /app/keys/private.pem
  JWT_KEY_ID: local-dev-key
  SMTP_HOST: mailhog
  SMTP_PORT: '1025'
  SMTP_USERNAME: ''
  SMTP_FROM_EMAIL: no-reply@automatic-system.local
  SMTP_FROM_NAME: Automatic System
  SMTP_USE_TLS: 'false'
  SMTP_USE_STARTTLS: 'false'
  FRONTEND_BASE_URL: http://localhost:3000
  KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
  OUTBOX_WORKER_COUNT: '4'
