services:
  brigade-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brigade
    ports:
      - "50054:50054"
    env_file:
      - .env
    environment:
      GRPC_PORT: "50054"
      DEPARTMENT_GRPC_ADDR: ${DEPARTMENT_GRPC_ADDR:-host.docker.internal:50053}
      PROFILE_GRPC_ADDR: ${PROFILE_GRPC_ADDR:-host.docker.internal:50055}
      KAFKA_BROKERS: ${KAFKA_BROKERS:-host.docker.internal:29092}
      OUTBOX_WORKER_COUNT: ${OUTBOX_WORKER_COUNT:-4}
      PROFILE_CONSUMER_WORKER_COUNT: ${PROFILE_CONSUMER_WORKER_COUNT:-4}
      PROFILE_RETRY_WORKER_COUNT: ${PROFILE_RETRY_WORKER_COUNT:-2}
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped

  postgres-brigade:
    image: postgis/postgis:16-3.4
    container_name: postgres-brigade
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_brigade_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${DB_USERNAME}\" -d \"$${DB_NAME}\""]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build: ./migrator
    container_name: brigade-migrator
    env_file:
      - .env
    depends_on:
      postgres-brigade:
        condition: service_healthy
    volumes:
      - ./scheme:/migrations
    environment:
      GOOSE_DRIVER: postgres
    command: >
      sh -c 'export GOOSE_DBSTRING="postgres://$${DB_USERNAME}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=$${SSLMODE}";
      goose -dir /migrations up'

volumes:
  postgres_brigade_data:
