---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: automatic-system
  labels:
    app.kubernetes.io/name: location-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: location-service
  ports:
  - name: grpc
    port: 50056
    targetPort: 50056
  - name: http
    port: 8080
    targetPort: 8080
