apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automatic-system-dev

resources:
  - ../../../base/apps

labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeSelectors: false

patches:
  - path: api-gateway-service.patch.yaml

images:
  - name: automatic-system/api-gateway
    newName: ghcr.io/fizzi-77/automatic-system-api-gateway
    newTag: sha-457fcddd7b6e
  - name: automatic-system/auth
    newName: ghcr.io/fizzi-77/automatic-system-auth
    newTag: sha-457fcddd7b6e
  - name: automatic-system/ticket
    newName: ghcr.io/fizzi-77/automatic-system-ticket
    newTag: sha-457fcddd7b6e
  - name: automatic-system/department
    newName: ghcr.io/fizzi-77/automatic-system-department
    newTag: sha-457fcddd7b6e
  - name: automatic-system/brigade
    newName: ghcr.io/fizzi-77/automatic-system-brigade
    newTag: sha-457fcddd7b6e
  - name: automatic-system/profile
    newName: ghcr.io/fizzi-77/automatic-system-profile
    newTag: sha-457fcddd7b6e
  - name: automatic-system/location
    newName: ghcr.io/fizzi-77/automatic-system-location
    newTag: sha-457fcddd7b6e
  - name: automatic-system/routing
    newName: ghcr.io/fizzi-77/automatic-system-routing
    newTag: sha-457fcddd7b6e
  - name: automatic-system/dispatch
    newName: ghcr.io/fizzi-77/automatic-system-dispatch
    newTag: sha-457fcddd7b6e
  - name: automatic-system/file
    newName: ghcr.io/fizzi-77/automatic-system-file
    newTag: sha-457fcddd7b6e
  - name: automatic-system/sla
    newName: ghcr.io/fizzi-77/automatic-system-sla
    newTag: sha-457fcddd7b6e
  - name: automatic-system/notification
    newName: ghcr.io/fizzi-77/automatic-system-notification
    newTag: sha-457fcddd7b6e
  - name: automatic-system/audit
    newName: ghcr.io/fizzi-77/automatic-system-audit
    newTag: sha-457fcddd7b6e
  - name: automatic-system/analytics
    newName: ghcr.io/fizzi-77/automatic-system-analytics
    newTag: sha-457fcddd7b6e
  - name: automatic-system/report
    newName: ghcr.io/fizzi-77/automatic-system-report
    newTag: sha-457fcddd7b6e
  - name: automatic-system/asset
    newName: ghcr.io/fizzi-77/automatic-system-asset
    newTag: sha-457fcddd7b6e
