apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: automatic-system
spec:
  selector:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: pool
  ports:
    - name: postgres
      port: 6432
      targetPort: postgres
