apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: application-prometheus-metrics
  namespace: automatic-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: automatic-system
  portLevelMtls:
    "9464":
      mode: DISABLE
