apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: prometheus-plaintext
  namespace: automatic-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  portLevelMtls:
    "9090":
      mode: DISABLE
