apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - ../../base/namespace
  - ../../base/observability
  - ../../mesh/policies
  - network
  - infra
  - migrations
  - apps
patches:
  - target:
      version: v1
      kind: Namespace
      name: automatic-system
    patch: |-
      - op: add
        path: /metadata/labels/istio-injection
        value: enabled
