---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: automatic-system
spec:
  selector:
    app: postgres-auth
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
  namespace: automatic-system
spec:
  serviceName: postgres-auth
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres-auth
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: auth_user
        - name: POSTGRES_PASSWORD
          value: change-me
        - name: POSTGRES_DB
          value: auth_db
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ticket
  namespace: automatic-system
spec:
  selector:
    app: postgres-ticket
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ticket
  namespace: automatic-system
spec:
  serviceName: postgres-ticket
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ticket
  template:
    metadata:
      labels:
        app: postgres-ticket
    spec:
      containers:
      - name: postgres-ticket
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: ticket_user
        - name: POSTGRES_PASSWORD
          value: change-me
        - name: POSTGRES_DB
          value: ticket_db
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-department
  namespace: automatic-system
spec:
  selector:
    app: postgres-department
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-department
  namespace: automatic-system
spec:
  serviceName: postgres-department
  replicas: 1
  selector:
    matchLabels:
      app: postgres-department
  template:
    metadata:
      labels:
        app: postgres-department
    spec:
      containers:
      - name: postgres-department
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: department_user
        - name: POSTGRES_PASSWORD
          value: change-me
        - name: POSTGRES_DB
          value: department_db
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-brigade
  namespace: automatic-system
spec:
  selector:
    app: postgres-brigade
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-brigade
  namespace: automatic-system
spec:
  serviceName: postgres-brigade
  replicas: 1
  selector:
    matchLabels:
      app: postgres-brigade
  template:
    metadata:
      labels:
        app: postgres-brigade
    spec:
      containers:
      - name: postgres-brigade
        image: postgis/postgis:16-3.4
        env:
        - name: POSTGRES_USER
          value: brigade_user
        - name: POSTGRES_PASSWORD
          value: change-me
        - name: POSTGRES_DB
          value: brigade_db
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-profile
  namespace: automatic-system
spec:
  selector:
    app: postgres-profile
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-profile
  namespace: automatic-system
spec:
  serviceName: postgres-profile
  replicas: 1
  selector:
    matchLabels:
      app: postgres-profile
  template:
    metadata:
      labels:
        app: postgres-profile
    spec:
      containers:
      - name: postgres-profile
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: profile_user
        - name: POSTGRES_PASSWORD
          value: change-me
        - name: POSTGRES_DB
          value: profile_db
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-location
  namespace: automatic-system
spec:
  selector:
    app: postgres-location
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-location
  namespace: automatic-system
spec:
  serviceName: postgres-location
  replicas: 1
  selector:
    matchLabels:
      app: postgres-location
  template:
    metadata:
      labels:
        app: postgres-location
    spec:
      containers:
      - name: postgres-location
        image: postgis/postgis:16-3.4
        env:
        - name: POSTGRES_USER
          value: location
        - name: POSTGRES_PASSWORD
          value: location
        - name: POSTGRES_DB
          value: location
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-routing
  namespace: automatic-system
spec:
  selector:
    app: postgres-routing
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-routing
  namespace: automatic-system
spec:
  serviceName: postgres-routing
  replicas: 1
  selector:
    matchLabels:
      app: postgres-routing
  template:
    metadata:
      labels:
        app: postgres-routing
    spec:
      containers:
      - name: postgres-routing
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: routing
        - name: POSTGRES_PASSWORD
          value: routing
        - name: POSTGRES_DB
          value: routing
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dispatch
  namespace: automatic-system
spec:
  selector:
    app: postgres-dispatch
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dispatch
  namespace: automatic-system
spec:
  serviceName: postgres-dispatch
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dispatch
  template:
    metadata:
      labels:
        app: postgres-dispatch
    spec:
      containers:
      - name: postgres-dispatch
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: dispatch
        - name: POSTGRES_PASSWORD
          value: dispatch
        - name: POSTGRES_DB
          value: dispatch
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-file
  namespace: automatic-system
spec:
  selector:
    app: postgres-file
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-file
  namespace: automatic-system
spec:
  serviceName: postgres-file
  replicas: 1
  selector:
    matchLabels:
      app: postgres-file
  template:
    metadata:
      labels:
        app: postgres-file
    spec:
      containers:
      - name: postgres-file
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: file
        - name: POSTGRES_PASSWORD
          value: file
        - name: POSTGRES_DB
          value: file
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sla
  namespace: automatic-system
spec:
  selector:
    app: postgres-sla
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sla
  namespace: automatic-system
spec:
  serviceName: postgres-sla
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sla
  template:
    metadata:
      labels:
        app: postgres-sla
    spec:
      containers:
      - name: postgres-sla
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: sla
        - name: POSTGRES_PASSWORD
          value: sla
        - name: POSTGRES_DB
          value: sla
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: automatic-system
spec:
  selector:
    app: postgres-notification
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notification
  namespace: automatic-system
spec:
  serviceName: postgres-notification
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      containers:
      - name: postgres-notification
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: notification
        - name: POSTGRES_PASSWORD
          value: notification
        - name: POSTGRES_DB
          value: notification
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-audit
  namespace: automatic-system
spec:
  selector:
    app: postgres-audit
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-audit
  namespace: automatic-system
spec:
  serviceName: postgres-audit
  replicas: 1
  selector:
    matchLabels:
      app: postgres-audit
  template:
    metadata:
      labels:
        app: postgres-audit
    spec:
      containers:
      - name: postgres-audit
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: audit
        - name: POSTGRES_PASSWORD
          value: audit
        - name: POSTGRES_DB
          value: audit
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-report
  namespace: automatic-system
spec:
  selector:
    app: postgres-report
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-report
  namespace: automatic-system
spec:
  serviceName: postgres-report
  replicas: 1
  selector:
    matchLabels:
      app: postgres-report
  template:
    metadata:
      labels:
        app: postgres-report
    spec:
      containers:
      - name: postgres-report
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: report
        - name: POSTGRES_PASSWORD
          value: report
        - name: POSTGRES_DB
          value: report
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-asset
  namespace: automatic-system
spec:
  selector:
    app: postgres-asset
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-asset
  namespace: automatic-system
spec:
  serviceName: postgres-asset
  replicas: 1
  selector:
    matchLabels:
      app: postgres-asset
  template:
    metadata:
      labels:
        app: postgres-asset
    spec:
      containers:
      - name: postgres-asset
        image: postgis/postgis:16-3.4
        env:
        - name: POSTGRES_USER
          value: asset
        - name: POSTGRES_PASSWORD
          value: asset
        - name: POSTGRES_DB
          value: asset
        ports:
        - name: main
          containerPort: 5432
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
