---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: automatic-system
  labels:
    app.kubernetes.io/name: routing-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: routing-service
  ports:
  - name: grpc
    port: 50057
    targetPort: 50057
