apiVersion: v1
kind: ConfigMap
metadata:
  name: department-service-config
  labels:
    app.kubernetes.io/name: department-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  GRPC_PORT: '50053'
  DB_HOST: postgres-department
  DB_PORT: '5432'
  DB_USERNAME: department_user
  DB_NAME: department_db
  SSLMODE: disable
  KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
  OUTBOX_WORKER_COUNT: '4'
