apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  INTERNAL_HTTP_PORT: '8084'
