apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - ../../../base/data
  - ../../../base/auxiliary
labels:
  - pairs:
      app.kubernetes.io/environment: local
    includeSelectors: false
