port 26379
sentinel monitor location-master redis-location-master 6379 2
sentinel down-after-milliseconds location-master 5000
sentinel failover-timeout location-master 10000
sentinel parallel-syncs location-master 1
