services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-jwt
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      KAFKA_BROKERS: host.docker.internal:29092
    depends_on:
      migrator:
        condition: service_completed_successfully
      
    volumes:
      - type: bind
        source: ../keys/private.pem
        target: /app/keys/private.pem
        read_only: true
        bind:
          create_host_path: false
    restart: unless-stopped

  postgres-auth:
    image: postgres:16
    container_name: auth-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${DB_USERNAME}\" -d \"$${DB_NAME}\""]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: auth-mailhog
    ports:
      - "${SMTP_PORT}:1025"
      - "8025:8025"
    restart: unless-stopped

  migrator:
    build: ./migrator
    container_name: auth-migrator
    env_file:
      - .env
    depends_on:
      postgres-auth:
        condition: service_healthy
    volumes:
      - ./scheme:/migrations
    environment:
      GOOSE_DRIVER: postgres
    command: >
      sh -c 'export GOOSE_DBSTRING="postgres://$${DB_USERNAME}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=$${SSLMODE}";
      goose -dir /migrations up'

volumes:
  postgres_auth_data:
