version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-jwt
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: auth-mailhog
    ports:
      - "${SMTP_PORT}:1025"
      - "8025:8025"
    restart: unless-stopped

  migrator:
    build: ./migrator
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scheme:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${SSLMODE}
    command: >
      sh -c "
        echo 'Running migrations...' &&
        goose -dir /migrations up
      "

volumes:
  postgres_auth_data: