apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - appProtocol: http
    name: http
    port: 3000
    targetPort: http
  selector:
    app: {{ ternary "frontend-primary" "frontend" .Values.canary.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: automatic-system
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ (index .Values.applications "frontend").replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: automatic-system
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: VALHALLA_URL
          value: http://valhalla:8002
        image: '{{ include "applications.image" (dict "root" $ "name" "frontend") }}'
        imagePullPolicy: {{ default (index .Values.applications "frontend").image.pullPolicy .Values.globalImage.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          periodSeconds: 10
        name: frontend
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 45
          httpGet:
            path: /
            port: http
          periodSeconds: 2
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      enableServiceLinks: false
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
