"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { api, config, type Session, type Ticket } from "./api";

const statusLabels:Record<string,string>={NEW:"Новые",ASSIGNED:"Назначены",IN_PROGRESS:"В работе",DONE:"Выполнены",CANCELED:"Отменены",CANCELLED:"Отменены"};
const priorityLabels:Record<string,string>={LOW:"Низкий",MEDIUM:"Средний",HIGH:"Высокий",EMERGENCY:"Экстренный"};
const assetTypeLabels:Record<string,string>={STREET_LIGHT:"Опоры освещения",BUS_STOP:"Остановки",TRAFFIC_LIGHT:"Светофоры",FIRE_HYDRANT:"Гидранты",ROAD_SIGN:"Дорожные знаки",ROAD:"Дороги"};
type Breakdown={key:string;count:number;percent?:number};
type Day={label:string;created:number;completed:number;canceled:number;slaBreaches:number};
type Overview={created:number;completed:number;canceled:number;active:number;completion_rate:number;avg_response_seconds:number;avg_resolution_seconds:number};
type SLA={response_warnings:number;response_breaches:number;resolution_warnings:number;resolution_breaches:number;completed:number;breach_rate:number};
type AssetGroup={key:string;incidents:number;repeated_incidents:number;repairs:number;critical_risk_updates:number};
type Assets={assets_created:number;incidents:number;repeated_incidents:number;repairs:number;inspections:number;critical_risk_updates:number;by_type:AssetGroup[];by_district:AssetGroup[]};
type DispatchFailureReason={reason:string;count:number;request_rate:number};
type DispatchFailureReasonDimension={reason:string;key:string;count:number;reason_percent:number};
type DispatchFailures={requested:number;failed:number;expired:number;canceled:number;failure_rate:number;by_stage:Breakdown[];by_code:Breakdown[];business_reasons:DispatchFailureReason[];reasons_by_department:DispatchFailureReasonDimension[];reasons_by_category:DispatchFailureReasonDimension[]};
type BrigadeWorkloadItem={brigade_id:string;incoming:number;assigned:number;completed:number;active:number};
type BrigadeWorkload={incoming:number;assigned:number;completed:number;active:number;unassigned_backlog:number;brigade_count:number;max_active:number;average_active:number;standard_deviation:number;coefficient_of_variation:number;gini:number;brigades:BrigadeWorkloadItem[]};
type ActiveWorkerGroup={dimension:string;key:string;active_members:number;available:number;on_shift:number};
type ActiveWorkers={active_members:number;available:number;on_shift:number;by_department:ActiveWorkerGroup[];by_brigade:ActiveWorkerGroup[]};
type LatencyDistribution={sample_count:number;average_seconds:number;median_seconds:number;p90_seconds:number;p95_seconds:number;p99_seconds:number};
type AssignmentFunnelStage={stage:string;count:number;conversion_from_previous:number;transition_time?:LatencyDistribution};
type AssignmentFunnel={stages:AssignmentFunnelStage[]};
type DispatchModeEffectiveness={mode:string;requested:number;assigned:number;success_rate:number;assignment_time:LatencyDistribution};
type DispatchEffectiveness={automatic:DispatchModeEffectiveness;manual:DispatchModeEffectiveness;manual_reassignment_available:boolean};
type QueueAgeBucket={range:string;count:number};
type OperationalInsights={departure_time:LatencyDistribution;queue_age:{active_unassigned:number;age:LatencyDistribution;buckets:QueueAgeBucket[]};routing:{routes:number;recalculations:number;cancellations:number;unreachable_candidate_rate:number;average_distance_km:number;kilometers_per_completed_ticket:number;eta_sample_count:number;eta_mean_absolute_error_seconds:number;eta_bias_seconds:number;eta_p95_absolute_error_seconds:number;eta_within_five_minutes_rate:number};capacity_forecast:{observed_days:number;average_daily_incoming:number;forecast_next_day:number;peak_hourly_incoming:number;required_brigades:number;formula:string}};
type ProjectionHealth={total_events:number;unknown_version_events:number;projected_events:number;missing_projection_events:number;projection_eligible_rate:number;projection_error_rate:number;freshness_seconds:number;ingestion_p95_seconds:number;topics:Array<{topic:string;total_events:number;unknown_version_events:number;projection_eligible_rate:number;freshness_seconds:number;ingestion_p95_seconds:number}>};
type DispatchOperation={operation_id:string;ticket_id:string;brigade_id:string;assignment_mode:string;status:string;failure_code:string;failure_stage:string;trace_id:string};
type BrigadePerformance={completed:number;execution_time:LatencyDistribution;sla_breaches:number;sla_breach_rate:number;repeated_asset_tickets:number;shift_metrics_available:boolean;shift_count:number;shift_hours:number;busy_hours:number;average_parallel_tasks:number;completed_per_shift:number;utilization_rate:number;brigades:Array<{brigade_id:string;completed:number;execution_time:LatencyDistribution;sla_breaches:number;sla_breach_rate:number;repeated_asset_tickets:number;shift_count:number;shift_hours:number;busy_hours:number;average_parallel_tasks:number;completed_per_shift:number;utilization_rate:number}>};
type Remote={overview:Overview;sla:SLA;days:Day[];statuses:Breakdown[];priorities:Breakdown[];departments:Breakdown[];categories:Breakdown[];assets:Assets;dispatchFailures:DispatchFailures;brigadeWorkload:BrigadeWorkload;activeWorkers:ActiveWorkers;assignmentFunnel:AssignmentFunnel;dispatchEffectiveness:DispatchEffectiveness;operationalInsights:OperationalInsights;projectionHealth:ProjectionHealth;dispatchOperations:DispatchOperation[];brigadePerformance:BrigadePerformance};

function duration(seconds:number){if(!seconds)return "0 сек";if(seconds<60)return `${Math.round(seconds)} сек`;if(seconds<3600)return `${Math.round(seconds/60)} мин`;const hours=Math.floor(seconds/3600),minutes=Math.round(seconds%3600/60);return `${hours} ч${minutes?` ${minutes} мин`:""}`}
function shortKey(value:string,prefix:string){if(!value)return "Не указано";return value.length>20?`${prefix} ${value.slice(0,8)}…${value.slice(-4)}`:value}
function dayValue(value:string|{seconds:number}){const date=typeof value==="string"?new Date(value):new Date(Number(value?.seconds||0)*1000);return date.toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}

export function AnalyticsPage({tickets,session,onNotice}:{tickets:Ticket[];session:Session;onNotice:(text:string)=>void}){
 const [period,setPeriod]=useState(30),[remote,setRemote]=useState<Remote>();
 const localDays=useMemo(()=>{const now=new Date();return Array.from({length:period},(_,i)=>{const date=new Date(now);date.setDate(now.getDate()-(period-i-1));const key=date.toISOString().slice(0,10),items=tickets.filter(t=>new Date(t.created_at*1000).toISOString().slice(0,10)===key);return{label:date.toLocaleDateString("ru-RU",{day:"2-digit",month:"short"}),created:items.length,completed:items.filter(t=>t.status==="DONE").length,canceled:items.filter(t=>["CANCELED","CANCELLED"].includes(t.status)).length,slaBreaches:0}})},[tickets,period]);
 useEffect(()=>{if(session.accessToken==="demo"){setRemote(undefined);return}let active=true;(async()=>{try{const to=new Date(),from=new Date();from.setDate(to.getDate()-period+1);const filter={from:from.toISOString(),to:to.toISOString(),...(session.user?.department_id?{department_id:session.user.department_id}:{})};const [overview,sla,daily,statuses,priorities,departments,categories,assets,dispatchFailures,brigadeWorkload,activeWorkers,assignmentFunnel,dispatchEffectiveness,operationalInsights,projectionHealth,dispatchOperations,brigadePerformance]=await Promise.all([
   api<Overview>(config.endpoints.analyticsOverview,{filter},"POST",session.accessToken),api<SLA>(config.endpoints.analyticsSlaSummary,{filter},"POST",session.accessToken),api<{items:Array<{day:string|{seconds:number};created:number;completed:number;canceled:number;sla_breaches:number}>}>(config.endpoints.analyticsDaily,{filter},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"status",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"priority",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"department",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"category",limit:100},"POST",session.accessToken),api<Assets>(config.endpoints.analyticsAssetsSummary,{filter},"POST",session.accessToken),
   api<DispatchFailures>(config.endpoints.analyticsDispatchFailures,{filter},"POST",session.accessToken),api<BrigadeWorkload>(config.endpoints.analyticsBrigadeWorkload,{filter},"POST",session.accessToken),api<ActiveWorkers>(config.endpoints.analyticsActiveWorkers,{filter},"POST",session.accessToken),api<AssignmentFunnel>(config.endpoints.analyticsAssignmentFunnel,{filter},"POST",session.accessToken),api<DispatchEffectiveness>(config.endpoints.analyticsDispatchEffectiveness,{filter},"POST",session.accessToken),api<OperationalInsights>(config.endpoints.analyticsOperationalInsights,{filter},"POST",session.accessToken),api<ProjectionHealth>(config.endpoints.analyticsProjectionHealth,{},"POST",session.accessToken),api<{items:DispatchOperation[]}>(config.endpoints.analyticsDispatchOperations,{filter},"POST",session.accessToken),api<BrigadePerformance>(config.endpoints.analyticsBrigadePerformance,{filter},"POST",session.accessToken),
  ]);if(active)setRemote({overview,sla,days:(daily.items||[]).map(x=>({label:dayValue(x.day),created:Number(x.created||0),completed:Number(x.completed||0),canceled:Number(x.canceled||0),slaBreaches:Number(x.sla_breaches||0)})),statuses:statuses.items||[],priorities:priorities.items||[],departments:departments.items||[],categories:categories.items||[],assets:{...assets,by_type:assets.by_type||[],by_district:assets.by_district||[]},dispatchFailures:{...dispatchFailures,by_stage:dispatchFailures.by_stage||[],by_code:dispatchFailures.by_code||[],business_reasons:dispatchFailures.business_reasons||[],reasons_by_department:dispatchFailures.reasons_by_department||[],reasons_by_category:dispatchFailures.reasons_by_category||[]},brigadeWorkload:{...brigadeWorkload,brigades:brigadeWorkload.brigades||[]},activeWorkers:{...activeWorkers,by_department:activeWorkers.by_department||[],by_brigade:activeWorkers.by_brigade||[]},assignmentFunnel:{stages:assignmentFunnel.stages||[]},dispatchEffectiveness,operationalInsights:{...operationalInsights,queue_age:{...operationalInsights.queue_age,buckets:operationalInsights.queue_age?.buckets||[]}},projectionHealth:{...projectionHealth,topics:projectionHealth.topics||[]},dispatchOperations:dispatchOperations.items||[],brigadePerformance:{...brigadePerformance,brigades:brigadePerformance.brigades||[]}})}catch(error){if(active)onNotice(error instanceof Error?error.message:"Не удалось загрузить аналитику")}})();return()=>{active=false}},[onNotice,period,session.accessToken,session.user?.department_id]);
 const days=remote?.days.length?remote.days:localDays,overview=remote?.overview,total=overview?.created??tickets.length,done=overview?.completed??tickets.filter(t=>t.status==="DONE").length,canceled=overview?.canceled??tickets.filter(t=>["CANCELED","CANCELLED"].includes(t.status)).length,activeCount=overview?.active??tickets.filter(t=>!["DONE","CANCELED","CANCELLED"].includes(t.status)).length,completion=overview?.completion_rate??(total?done/total*100:0);
 const localBreakdown=(values:Record<string,string>,field:"status"|"priority")=>Object.keys(values).map(key=>({key,count:tickets.filter(t=>t[field]===key).length})).filter(x=>x.count);
 const statuses=remote?.statuses.length?remote.statuses:localBreakdown(statusLabels,"status"),priorityRows=remote?.priorities.length?remote.priorities:localBreakdown(priorityLabels,"priority"),emergency=priorityRows.find(x=>x.key==="EMERGENCY")?.count||0,max=Math.max(1,...days.flatMap(x=>[x.created,x.completed,x.canceled,x.slaBreaches]));
 const sla=remote?.sla||{response_warnings:0,response_breaches:0,resolution_warnings:0,resolution_breaches:0,completed:done,breach_rate:0},assets=remote?.assets||{assets_created:0,incidents:0,repeated_incidents:0,repairs:0,inspections:0,critical_risk_updates:0,by_type:[],by_district:[]};
 const dispatchFailures=remote?.dispatchFailures||{requested:0,failed:0,expired:0,canceled:0,failure_rate:0,by_stage:[],by_code:[],business_reasons:[],reasons_by_department:[],reasons_by_category:[]},workload=remote?.brigadeWorkload||{incoming:0,assigned:0,completed:0,active:0,unassigned_backlog:0,brigade_count:0,max_active:0,average_active:0,standard_deviation:0,coefficient_of_variation:0,gini:0,brigades:[]},workers=remote?.activeWorkers||{active_members:0,available:0,by_department:[],by_brigade:[]};
 const funnel=remote?.assignmentFunnel||{stages:[]},funnelLabels:Record<string,string>={REQUESTED:"Запрошено",CANDIDATES_FOUND:"Найдены кандидаты",RESERVED:"Бригада зарезервирована",ROUTE_BUILT:"Маршрут построен",ASSIGNED:"Назначено"},failureReasonLabels:Record<string,string>={NO_SUITABLE_BRIGADE:"Нет подходящей бригады",NO_ROUTE:"Нет доступного маршрута",RESERVATION_EXPIRED:"Истекла reservation"};
 const insights=remote?.operationalInsights||{departure_time:{sample_count:0,average_seconds:0,median_seconds:0,p90_seconds:0,p95_seconds:0,p99_seconds:0},queue_age:{active_unassigned:0,age:{sample_count:0,average_seconds:0,median_seconds:0,p90_seconds:0,p95_seconds:0,p99_seconds:0},buckets:[]},routing:{routes:0,recalculations:0,cancellations:0,unreachable_candidate_rate:0,average_distance_km:0,kilometers_per_completed_ticket:0,eta_sample_count:0,eta_mean_absolute_error_seconds:0,eta_bias_seconds:0,eta_p95_absolute_error_seconds:0,eta_within_five_minutes_rate:0},capacity_forecast:{observed_days:0,average_daily_incoming:0,forecast_next_day:0,peak_hourly_incoming:0,required_brigades:0,formula:""}};
 const effectiveness=remote?.dispatchEffectiveness||{automatic:{mode:"AUTOMATIC",requested:0,assigned:0,success_rate:0,assignment_time:{sample_count:0,average_seconds:0,median_seconds:0,p90_seconds:0,p95_seconds:0,p99_seconds:0}},manual:{mode:"MANUAL",requested:0,assigned:0,success_rate:0,assignment_time:{sample_count:0,average_seconds:0,median_seconds:0,p90_seconds:0,p95_seconds:0,p99_seconds:0}},manual_reassignment_available:false},projectionHealth=remote?.projectionHealth||{total_events:0,unknown_version_events:0,projected_events:0,missing_projection_events:0,projection_eligible_rate:0,projection_error_rate:0,freshness_seconds:0,ingestion_p95_seconds:0,topics:[]},dispatchOperations=remote?.dispatchOperations||[];
 const performance=remote?.brigadePerformance||{completed:0,execution_time:{sample_count:0,average_seconds:0,median_seconds:0,p90_seconds:0,p95_seconds:0,p99_seconds:0},sla_breaches:0,sla_breach_rate:0,repeated_asset_tickets:0,shift_metrics_available:false,shift_count:0,shift_hours:0,busy_hours:0,average_parallel_tasks:0,completed_per_shift:0,utilization_rate:0,brigades:[]};
 const rows=(items:Breakdown[],labels:Record<string,string>,prefix:string)=>items.map(item=>({label:labels[item.key]||shortKey(item.key,prefix),value:Number(item.count||0),percent:Number(item.percent||0)}));
 return <section className="content-page analytics-page"><div className="page-toolbar"><div><span className="eyebrow">Analytics Service</span><h2>Динамика обращений</h2><p>Все показатели заявок, SLA и городской инфраструктуры</p></div><div className="analytics-period">{[7,14,30,90].map(n=><button key={n} className={period===n?"active":""} onClick={()=>setPeriod(n)}>{n} дней</button>)}</div></div><HealthSection health={projectionHealth}/><EffectivenessSection value={effectiveness}/><DispatchOperationsSection items={dispatchOperations}/><PerformanceSection value={performance}/><BalanceSection workload={workload}/><InsightsSection insights={insights}/>
 <div className="analytics-kpis analytics-kpis-main"><Metric title="Создано обращений" value={total} note="за выбранный период"/><Metric title="Активные" value={activeCount} note="ещё требуют исполнения"/><Metric title="Выполнено" value={done} note={`${Math.round(completion)}% от созданных`}/><Metric title="Отменено" value={canceled} note="закрыто без выполнения"/><Metric title="Средняя реакция" value={duration(overview?.avg_response_seconds||0)} note="до назначения или начала работ" text/><Metric title="Среднее решение" value={duration(overview?.avg_resolution_seconds||0)} note="от создания до выполнения" text/><Metric title="Экстренные" value={emergency} note="наивысший приоритет"/><Metric title="Исполнение" value={`${Math.round(completion)}%`} note="коэффициент завершения"/></div>
 <div className="analytics-grid analytics-grid-full"><article className="trend-card analytics-wide"><div className="analytics-card-head"><div><h3>Обращения и SLA по дням</h3><p>Создание, выполнение, отмены и нарушения контрольных сроков</p></div><div className="chart-legend"><span><i/>Создано</span><span><i/>Выполнено</span><span><i/>Отменено</span><span><i/>SLA нарушен</span></div></div><div className="trend-chart">{days.map((day,index)=><div className="trend-column" key={`${day.label}-${index}`}><div className="trend-bars"><i style={{height:`${Math.max(day.created?4:0,day.created/max*100)}%`}} title={`Создано: ${day.created}`}/><i style={{height:`${Math.max(day.completed?4:0,day.completed/max*100)}%`}} title={`Выполнено: ${day.completed}`}/><i style={{height:`${Math.max(day.canceled?4:0,day.canceled/max*100)}%`}} title={`Отменено: ${day.canceled}`}/><i style={{height:`${Math.max(day.slaBreaches?4:0,day.slaBreaches/max*100)}%`}} title={`Нарушения SLA: ${day.slaBreaches}`}/></div><span>{day.label}</span></div>)}</div></article>
 <BreakdownCard title="Обращения по статусам" subtitle="Текущее распределение очереди" items={rows(statuses,statusLabels,"Статус")}/><BreakdownCard title="Обращения по приоритету" subtitle="Структура поступивших обращений" items={rows(priorityRows,priorityLabels,"Приоритет")}/><BreakdownCard title="По департаментам" subtitle="Нагрузка городских служб" items={rows(remote?.departments||[],{},"Департамент")}/><BreakdownCard title="По категориям" subtitle="Основные типы городских проблем" items={rows(remote?.categories||[],{},"Категория")}/></div>
 <AnalyticsSection eyebrow="Операционный контур" title="Диспетчеризация и ресурсы" side={`${Math.round(dispatchFailures.failure_rate||0)}% неуспешных назначений`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Запросы назначения" value={dispatchFailures.requested||0} note="операций Dispatch"/><Metric title="Ошибки" value={dispatchFailures.failed||0} note="статус FAILED"/><Metric title="Истекли" value={dispatchFailures.expired||0} note="статус EXPIRED"/><Metric title="Отменены" value={dispatchFailures.canceled||0} note="статус CANCELED"/><Metric title="Активные у бригад" value={workload.active||0} note="ASSIGNED / IN_PROGRESS"/><Metric title="Без назначения" value={workload.unassigned_backlog||0} note="backlog NEW"/></div><div className="analytics-grid analytics-grid-full"><BreakdownCard title="Воронка назначения" subtitle="Конверсия этапа; в подписи показан p95 перехода" items={funnel.stages.map(stage=>({label:`${funnelLabels[stage.stage]||stage.stage}${stage.transition_time?.sample_count?` · p95 ${duration(stage.transition_time.p95_seconds)}`:""}`,value:Number(stage.count||0),percent:Number(stage.conversion_from_previous||0)}))}/><BreakdownCard title="Ключевые причины неназначения" subtitle="Доля от всех запросов Dispatch" items={dispatchFailures.business_reasons.map(item=>({label:failureReasonLabels[item.reason]||item.reason,value:Number(item.count||0),percent:Number(item.request_rate||0)}))}/><BreakdownCard title="Top причин по департаментам" subtitle="Доля департамента внутри каждой причины" items={dispatchFailures.reasons_by_department.map(item=>({label:`${failureReasonLabels[item.reason]||item.reason} · ${shortKey(item.key,"Департамент")}`,value:Number(item.count||0),percent:Number(item.reason_percent||0)}))}/><BreakdownCard title="Top причин по категориям" subtitle="Доля категории внутри каждой причины" items={dispatchFailures.reasons_by_category.map(item=>({label:`${failureReasonLabels[item.reason]||item.reason} · ${shortKey(item.key,"Категория")}`,value:Number(item.count||0),percent:Number(item.reason_percent||0)}))}/><BreakdownCard title="Причины ошибок Dispatch" subtitle="Неуспешные операции по коду" items={rows(dispatchFailures.by_code,{},"Причина")}/><BreakdownCard title="Стадии отказа" subtitle="Этап, на котором остановилось назначение" items={rows(dispatchFailures.by_stage,{},"Стадия")}/><BreakdownCard title="Нагрузка бригад" subtitle="Текущие активные заявки" items={workload.brigades.map(item=>({label:shortKey(item.brigade_id,"Бригада"),value:Number(item.active||0),percent:0}))}/><BreakdownCard title="Доступные работники" subtitle={`${workers.available||0} из ${workers.active_members||0} активных участников`} items={workers.by_brigade.map(item=>({label:shortKey(item.key,"Бригада"),value:Number(item.available||0),percent:item.active_members?Number(item.available||0)/Number(item.active_members)*100:0}))}/></div></AnalyticsSection>
 <AnalyticsSection eyebrow="Контроль сроков" title="Состояние SLA" side={`${Math.round(sla.breach_rate||0)}% нарушений`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Предупреждения реакции" value={sla.response_warnings||0} note="срок реакции приближается"/><Metric title="Нарушения реакции" value={sla.response_breaches||0} note="реакция просрочена"/><Metric title="Предупреждения выполнения" value={sla.resolution_warnings||0} note="срок выполнения приближается"/><Metric title="Нарушения выполнения" value={sla.resolution_breaches||0} note="выполнение просрочено"/><Metric title="Завершено под SLA" value={sla.completed||0} note="контролей закрыто"/><Metric title="Доля нарушений" value={`${Math.round(sla.breach_rate||0)}%`} note="по событиям SLA Service"/></div></AnalyticsSection>
 <AnalyticsSection eyebrow="Городские объекты" title="Аналитика инфраструктуры" side="События Asset Service"><div className="analytics-kpis analytics-kpis-six"><Metric title="Создано паспортов" value={assets.assets_created||0} note="новых объектов"/><Metric title="Инциденты" value={assets.incidents||0} note="зарегистрировано"/><Metric title="Повторные инциденты" value={assets.repeated_incidents||0} note="требуют анализа причин"/><Metric title="Ремонты" value={assets.repairs||0} note="выполнено работ"/><Metric title="Осмотры" value={assets.inspections||0} note="проведено проверок"/><Metric title="Критический риск" value={assets.critical_risk_updates||0} note="опасных обновлений риска"/></div>{(assets.by_type.length>0||assets.by_district.length>0)&&<div className="asset-analytics-grid"><AssetAnalyticsCard title="По типам объектов" items={assets.by_type} labels={assetTypeLabels}/><AssetAnalyticsCard title="По районам" items={assets.by_district} labels={{}}/></div>}</AnalyticsSection></section>;
}

function Metric({title,value,note,text=false}:{title:string;value:string|number;note:string;text?:boolean}){return <article><span>{title}</span><b className={text?"metric-text":""}>{value}</b><small>{note}</small></article>}
function BalanceSection({workload}:{workload:BrigadeWorkload}){return <AnalyticsSection eyebrow="Распределение ресурсов" title="Баланс нагрузки бригад" side={`Gini ${(workload.gini||0).toFixed(2)}`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Бригад в выборке" value={workload.brigade_count||0} note="включая простаивающие"/><Metric title="Максимальная нагрузка" value={workload.max_active||0} note="активных заявок на бригаду"/><Metric title="Средняя нагрузка" value={(workload.average_active||0).toFixed(2)} note="активных заявок"/><Metric title="Стандартное отклонение" value={(workload.standard_deviation||0).toFixed(2)} note="разброс нагрузки"/><Metric title="Коэффициент вариации" value={(workload.coefficient_of_variation||0).toFixed(2)} note="σ / среднее"/><Metric title="Gini" value={(workload.gini||0).toFixed(2)} note="0 — равномерно, 1 — перекос"/></div></AnalyticsSection>}
function InsightsSection({insights}:{insights:OperationalInsights}){const queue=insights.queue_age,routing=insights.routing,forecast=insights.capacity_forecast;return <AnalyticsSection eyebrow="Планирование" title="Очередь, выезд и маршруты" side={`Прогноз: ${Math.round(forecast.forecast_next_day||0)} заявок`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Среднее до выезда" value={duration(insights.departure_time?.average_seconds||0)} note={`p95 ${duration(insights.departure_time?.p95_seconds||0)}`} text/><Metric title="Возраст очереди p95" value={duration(queue.age?.p95_seconds||0)} note={`${queue.active_unassigned||0} без назначения`} text/><Metric title="Перестроения" value={routing.recalculations||0} note={`${routing.routes||0} маршрутов`}/><Metric title="Отмены маршрутов" value={routing.cancellations||0} note={`${(routing.unreachable_candidate_rate||0).toFixed(1)}% кандидатов недостижимы`}/><Metric title="Ошибка ETA" value={routing.eta_sample_count?duration(routing.eta_mean_absolute_error_seconds||0):"Нет данных"} note={`${routing.eta_sample_count||0} arrivals · ${(routing.eta_within_five_minutes_rate||0).toFixed(1)}% ±5 мин`} text/><Metric title="Требуется бригад" value={forecast.required_brigades||0} note={`${forecast.observed_days||0} дней наблюдений`}/></div><div className="analytics-grid analytics-grid-full"><BreakdownCard title="Возраст неназначенной очереди" subtitle="Интервалы в минутах" items={(queue.buckets||[]).map(item=>({label:item.range,value:Number(item.count||0),percent:0}))}/></div></AnalyticsSection>}
function HealthSection({health}:{health:ProjectionHealth}){return <AnalyticsSection eyebrow="Качество данных" title="Состояние аналитических проекций" side={`${(health.projection_eligible_rate||0).toFixed(1)}% пригодных событий`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Событий" value={health.total_events||0} note={`${health.projected_events||0} в read model`}/><Metric title="Ошибки проекции" value={health.missing_projection_events||0} note={`${(health.projection_error_rate||0).toFixed(2)}% отсутствуют`}/><Metric title="Неизвестные версии" value={health.unknown_version_events||0} note="исключены из проекций"/><Metric title="Freshness" value={duration(health.freshness_seconds||0)} note="с последнего события" text/><Metric title="Ingestion p95" value={duration(health.ingestion_p95_seconds||0)} note="event → ClickHouse" text/><Metric title="Топиков" value={health.topics?.length||0} note="источников данных"/></div></AnalyticsSection>}
function EffectivenessSection({value}:{value:DispatchEffectiveness}){const modes=[value.automatic,value.manual];return <AnalyticsSection eyebrow="Автоматизация" title="Эффективность назначения" side={value.manual_reassignment_available?"Переназначения доступны":"Переназначения ещё не измеряются"}><div className="analytics-grid analytics-grid-full">{modes.map(mode=><BreakdownCard key={mode.mode} title={mode.mode==="AUTOMATIC"?"Автоматическое назначение":"Ручное назначение"} subtitle={`Среднее ${duration(mode.assignment_time?.average_seconds||0)} · p95 ${duration(mode.assignment_time?.p95_seconds||0)}`} items={[{label:"Запрошено",value:Number(mode.requested||0),percent:100},{label:"Назначено",value:Number(mode.assigned||0),percent:Number(mode.success_rate||0)}]}/>)}</div></AnalyticsSection>}
function DispatchOperationsSection({items}:{items:DispatchOperation[]}){return <AnalyticsSection eyebrow="Drill-down" title="Последние операции Dispatch" side={`${items.length} операций`}><div className="breakdown-card"><div className="breakdown-list">{items.length?items.map(item=><div key={item.operation_id}><span title={item.operation_id}>{shortKey(item.ticket_id||item.operation_id,"Операция")}</span><span>{item.status||"—"}{item.failure_code?` · ${item.failure_code}`:""}</span><b>{item.trace_id?<a href={`/jaeger/search?traceID=${encodeURIComponent(item.trace_id)}`} target="_blank" rel="noreferrer">Trace</a>:"—"}</b></div>):<p className="analytics-empty">Нет операций за выбранный период.</p>}</div></div></AnalyticsSection>}
function PerformanceSection({value}:{value:BrigadePerformance}){return <AnalyticsSection eyebrow="Исполнение" title="Производительность бригад" side={value.shift_metrics_available?`${value.shift_count||0} фактических смен`:"Без данных о сменах"}><div className="analytics-kpis analytics-kpis-six"><Metric title="Завершено" value={value.completed||0} note="заявок за период"/><Metric title="Среднее выполнение" value={duration(value.execution_time?.average_seconds||0)} note={`p95 ${duration(value.execution_time?.p95_seconds||0)}`} text/><Metric title="SLA breaches" value={value.sla_breaches||0} note={`${(value.sla_breach_rate||0).toFixed(1)}% завершённых`}/><Metric title="Повторные по объекту" value={value.repeated_asset_tickets||0} note="после первого обращения"/><Metric title="Завершено на смену" value={value.shift_metrics_available?(value.completed_per_shift||0).toFixed(2):"—"} note={value.shift_metrics_available?`${(value.shift_hours||0).toFixed(1)} смено-часов`:"нужны события начала смены"} text/><Metric title="Утилизация смен" value={value.shift_metrics_available?`${(value.utilization_rate||0).toFixed(1)}%`:"—"} note="время исполнения / смено-часы" text/></div><div className="analytics-grid analytics-grid-full"><BreakdownCard title="Завершено по бригадам" subtitle="Текущий период" items={(value.brigades||[]).map(item=>({label:shortKey(item.brigade_id,"Бригада"),value:Number(item.completed||0),percent:0}))}/></div></AnalyticsSection>}
function AnalyticsSection({eyebrow,title,side,children}:{eyebrow:string;title:string;side:string;children:React.ReactNode}){return <section className="analytics-section"><div className="analytics-section-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><b>{side}</b></div>{children}</section>}
function BreakdownCard({title,subtitle,items}:{title:string;subtitle:string;items:Array<{label:string;value:number;percent:number}>}){const max=Math.max(1,...items.map(x=>x.value));return <article className="breakdown-card"><h3>{title}</h3><p>{subtitle}</p><div className="breakdown-list">{items.length?items.map((x,index)=><div key={`${x.label}-${index}`}><span title={x.label}>{x.label}</span><div><i style={{width:`${x.percent||x.value/max*100}%`}}/></div><b>{x.value}</b></div>):<p className="analytics-empty">Нет данных за выбранный период.</p>}</div></article>}
function AssetAnalyticsCard({title,items,labels}:{title:string;items:AssetGroup[];labels:Record<string,string>}){return <article className="asset-analytics-card"><h4>{title}</h4><div className="asset-analytics-head"><span>Группа</span><span>Инциденты</span><span>Повторные</span><span>Ремонты</span><span>Критический риск</span></div>{items.map(item=><div className="asset-analytics-row" key={item.key}><b>{labels[item.key]||item.key}</b><span>{item.incidents||0}</span><span>{item.repeated_incidents||0}</span><span>{item.repairs||0}</span><span>{item.critical_risk_updates||0}</span></div>)}</article>}
