"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { api, config, type Session, type Ticket } from "./api";

const statusLabels:Record<string,string>={NEW:"Новые",ASSIGNED:"Назначены",IN_PROGRESS:"В работе",DONE:"Выполнены",CANCELED:"Отменены",CANCELLED:"Отменены"};
const priorityLabels:Record<string,string>={LOW:"Низкий",MEDIUM:"Средний",HIGH:"Высокий",EMERGENCY:"Экстренный"};
const assetTypeLabels:Record<string,string>={STREET_LIGHT:"Опоры освещения",BUS_STOP:"Остановки",TRAFFIC_LIGHT:"Светофоры",FIRE_HYDRANT:"Гидранты",ROAD_SIGN:"Дорожные знаки",ROAD:"Дороги"};
type Breakdown={key:string;count:number;percent?:number};
type Day={label:string;created:number;completed:number;canceled:number;slaBreaches:number};
type Overview={created:number;completed:number;canceled:number;active:number;completion_rate:number;avg_response_seconds:number;avg_resolution_seconds:number};
type SLA={response_warnings:number;response_breaches:number;resolution_warnings:number;resolution_breaches:number;completed:number;breach_rate:number};
type AssetGroup={key:string;incidents:number;repeated_incidents:number;repairs:number;critical_risk_updates:number};
type Assets={assets_created:number;incidents:number;repeated_incidents:number;repairs:number;inspections:number;critical_risk_updates:number;by_type:AssetGroup[];by_district:AssetGroup[]};
type Remote={overview:Overview;sla:SLA;days:Day[];statuses:Breakdown[];priorities:Breakdown[];departments:Breakdown[];categories:Breakdown[];assets:Assets};

function duration(seconds:number){if(!seconds)return "0 мин";if(seconds<3600)return `${Math.round(seconds/60)} мин`;const hours=Math.floor(seconds/3600),minutes=Math.round(seconds%3600/60);return `${hours} ч${minutes?` ${minutes} мин`:""}`}
function shortKey(value:string,prefix:string){if(!value)return "Не указано";return value.length>20?`${prefix} ${value.slice(0,8)}…${value.slice(-4)}`:value}
function dayValue(value:string|{seconds:number}){const date=typeof value==="string"?new Date(value):new Date(Number(value?.seconds||0)*1000);return date.toLocaleDateString("ru-RU",{day:"2-digit",month:"short"})}

export function AnalyticsPage({tickets,session,onNotice}:{tickets:Ticket[];session:Session;onNotice:(text:string)=>void}){
 const [period,setPeriod]=useState(30),[remote,setRemote]=useState<Remote>();
 const localDays=useMemo(()=>{const now=new Date();return Array.from({length:period},(_,i)=>{const date=new Date(now);date.setDate(now.getDate()-(period-i-1));const key=date.toISOString().slice(0,10),items=tickets.filter(t=>new Date(t.created_at*1000).toISOString().slice(0,10)===key);return{label:date.toLocaleDateString("ru-RU",{day:"2-digit",month:"short"}),created:items.length,completed:items.filter(t=>t.status==="DONE").length,canceled:items.filter(t=>["CANCELED","CANCELLED"].includes(t.status)).length,slaBreaches:0}})},[tickets,period]);
 useEffect(()=>{if(session.accessToken==="demo"){setRemote(undefined);return}let active=true;(async()=>{try{const to=new Date(),from=new Date();from.setDate(to.getDate()-period+1);const filter={from:from.toISOString(),to:to.toISOString(),...(session.user?.department_id?{department_id:session.user.department_id}:{})};const [overview,sla,daily,statuses,priorities,departments,categories,assets]=await Promise.all([
   api<Overview>(config.endpoints.analyticsOverview,{filter},"POST",session.accessToken),api<SLA>(config.endpoints.analyticsSlaSummary,{filter},"POST",session.accessToken),api<{items:Array<{day:string|{seconds:number};created:number;completed:number;canceled:number;sla_breaches:number}>}>(config.endpoints.analyticsDaily,{filter},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"status",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"priority",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"department",limit:100},"POST",session.accessToken),api<{items:Breakdown[]}>(config.endpoints.analyticsBreakdown,{filter,dimension:"category",limit:100},"POST",session.accessToken),api<Assets>(config.endpoints.analyticsAssetsSummary,{filter},"POST",session.accessToken),
  ]);if(active)setRemote({overview,sla,days:(daily.items||[]).map(x=>({label:dayValue(x.day),created:Number(x.created||0),completed:Number(x.completed||0),canceled:Number(x.canceled||0),slaBreaches:Number(x.sla_breaches||0)})),statuses:statuses.items||[],priorities:priorities.items||[],departments:departments.items||[],categories:categories.items||[],assets:{...assets,by_type:assets.by_type||[],by_district:assets.by_district||[]}})}catch(error){if(active)onNotice(error instanceof Error?error.message:"Не удалось загрузить аналитику")}})();return()=>{active=false}},[onNotice,period,session.accessToken,session.user?.department_id]);
 const days=remote?.days.length?remote.days:localDays,overview=remote?.overview,total=overview?.created??tickets.length,done=overview?.completed??tickets.filter(t=>t.status==="DONE").length,canceled=overview?.canceled??tickets.filter(t=>["CANCELED","CANCELLED"].includes(t.status)).length,activeCount=overview?.active??tickets.filter(t=>!["DONE","CANCELED","CANCELLED"].includes(t.status)).length,completion=overview?.completion_rate??(total?done/total*100:0);
 const localBreakdown=(values:Record<string,string>,field:"status"|"priority")=>Object.keys(values).map(key=>({key,count:tickets.filter(t=>t[field]===key).length})).filter(x=>x.count);
 const statuses=remote?.statuses.length?remote.statuses:localBreakdown(statusLabels,"status"),priorityRows=remote?.priorities.length?remote.priorities:localBreakdown(priorityLabels,"priority"),emergency=priorityRows.find(x=>x.key==="EMERGENCY")?.count||0,max=Math.max(1,...days.flatMap(x=>[x.created,x.completed,x.canceled,x.slaBreaches]));
 const sla=remote?.sla||{response_warnings:0,response_breaches:0,resolution_warnings:0,resolution_breaches:0,completed:done,breach_rate:0},assets=remote?.assets||{assets_created:0,incidents:0,repeated_incidents:0,repairs:0,inspections:0,critical_risk_updates:0,by_type:[],by_district:[]};
 const rows=(items:Breakdown[],labels:Record<string,string>,prefix:string)=>items.map(item=>({label:labels[item.key]||shortKey(item.key,prefix),value:Number(item.count||0),percent:Number(item.percent||0)}));
 return <section className="content-page analytics-page"><div className="page-toolbar"><div><span className="eyebrow">Analytics Service</span><h2>Динамика обращений</h2><p>Все показатели заявок, SLA и городской инфраструктуры</p></div><div className="analytics-period">{[7,14,30,90].map(n=><button key={n} className={period===n?"active":""} onClick={()=>setPeriod(n)}>{n} дней</button>)}</div></div>
 <div className="analytics-kpis analytics-kpis-main"><Metric title="Создано обращений" value={total} note="за выбранный период"/><Metric title="Активные" value={activeCount} note="ещё требуют исполнения"/><Metric title="Выполнено" value={done} note={`${Math.round(completion)}% от созданных`}/><Metric title="Отменено" value={canceled} note="закрыто без выполнения"/><Metric title="Средняя реакция" value={duration(overview?.avg_response_seconds||0)} note="до назначения или начала работ" text/><Metric title="Среднее решение" value={duration(overview?.avg_resolution_seconds||0)} note="от создания до выполнения" text/><Metric title="Экстренные" value={emergency} note="наивысший приоритет"/><Metric title="Исполнение" value={`${Math.round(completion)}%`} note="коэффициент завершения"/></div>
 <div className="analytics-grid analytics-grid-full"><article className="trend-card analytics-wide"><div className="analytics-card-head"><div><h3>Обращения и SLA по дням</h3><p>Создание, выполнение, отмены и нарушения контрольных сроков</p></div><div className="chart-legend"><span><i/>Создано</span><span><i/>Выполнено</span><span><i/>Отменено</span><span><i/>SLA нарушен</span></div></div><div className="trend-chart">{days.map((day,index)=><div className="trend-column" key={`${day.label}-${index}`}><div className="trend-bars"><i style={{height:`${Math.max(day.created?4:0,day.created/max*100)}%`}} title={`Создано: ${day.created}`}/><i style={{height:`${Math.max(day.completed?4:0,day.completed/max*100)}%`}} title={`Выполнено: ${day.completed}`}/><i style={{height:`${Math.max(day.canceled?4:0,day.canceled/max*100)}%`}} title={`Отменено: ${day.canceled}`}/><i style={{height:`${Math.max(day.slaBreaches?4:0,day.slaBreaches/max*100)}%`}} title={`Нарушения SLA: ${day.slaBreaches}`}/></div><span>{day.label}</span></div>)}</div></article>
 <BreakdownCard title="Обращения по статусам" subtitle="Текущее распределение очереди" items={rows(statuses,statusLabels,"Статус")}/><BreakdownCard title="Обращения по приоритету" subtitle="Структура поступивших обращений" items={rows(priorityRows,priorityLabels,"Приоритет")}/><BreakdownCard title="По департаментам" subtitle="Нагрузка городских служб" items={rows(remote?.departments||[],{},"Департамент")}/><BreakdownCard title="По категориям" subtitle="Основные типы городских проблем" items={rows(remote?.categories||[],{},"Категория")}/></div>
 <AnalyticsSection eyebrow="Контроль сроков" title="Состояние SLA" side={`${Math.round(sla.breach_rate||0)}% нарушений`}><div className="analytics-kpis analytics-kpis-six"><Metric title="Предупреждения реакции" value={sla.response_warnings||0} note="срок реакции приближается"/><Metric title="Нарушения реакции" value={sla.response_breaches||0} note="реакция просрочена"/><Metric title="Предупреждения выполнения" value={sla.resolution_warnings||0} note="срок выполнения приближается"/><Metric title="Нарушения выполнения" value={sla.resolution_breaches||0} note="выполнение просрочено"/><Metric title="Завершено под SLA" value={sla.completed||0} note="контролей закрыто"/><Metric title="Доля нарушений" value={`${Math.round(sla.breach_rate||0)}%`} note="по событиям SLA Service"/></div></AnalyticsSection>
 <AnalyticsSection eyebrow="Городские объекты" title="Аналитика инфраструктуры" side="События Asset Service"><div className="analytics-kpis analytics-kpis-six"><Metric title="Создано паспортов" value={assets.assets_created||0} note="новых объектов"/><Metric title="Инциденты" value={assets.incidents||0} note="зарегистрировано"/><Metric title="Повторные инциденты" value={assets.repeated_incidents||0} note="требуют анализа причин"/><Metric title="Ремонты" value={assets.repairs||0} note="выполнено работ"/><Metric title="Осмотры" value={assets.inspections||0} note="проведено проверок"/><Metric title="Критический риск" value={assets.critical_risk_updates||0} note="опасных обновлений риска"/></div>{(assets.by_type.length>0||assets.by_district.length>0)&&<div className="asset-analytics-grid"><AssetAnalyticsCard title="По типам объектов" items={assets.by_type} labels={assetTypeLabels}/><AssetAnalyticsCard title="По районам" items={assets.by_district} labels={{}}/></div>}</AnalyticsSection></section>;
}

function Metric({title,value,note,text=false}:{title:string;value:string|number;note:string;text?:boolean}){return <article><span>{title}</span><b className={text?"metric-text":""}>{value}</b><small>{note}</small></article>}
function AnalyticsSection({eyebrow,title,side,children}:{eyebrow:string;title:string;side:string;children:React.ReactNode}){return <section className="analytics-section"><div className="analytics-section-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><b>{side}</b></div>{children}</section>}
function BreakdownCard({title,subtitle,items}:{title:string;subtitle:string;items:Array<{label:string;value:number;percent:number}>}){const max=Math.max(1,...items.map(x=>x.value));return <article className="breakdown-card"><h3>{title}</h3><p>{subtitle}</p><div className="breakdown-list">{items.length?items.map((x,index)=><div key={`${x.label}-${index}`}><span title={x.label}>{x.label}</span><div><i style={{width:`${x.percent||x.value/max*100}%`}}/></div><b>{x.value}</b></div>):<p className="analytics-empty">Пока нет данных за этот период.</p>}</div></article>}
function AssetAnalyticsCard({title,items,labels}:{title:string;items:AssetGroup[];labels:Record<string,string>}){return <article className="asset-analytics-card"><h4>{title}</h4><div className="asset-analytics-head"><span>Группа</span><span>Инциденты</span><span>Повторные</span><span>Ремонты</span><span>Критический риск</span></div>{items.map(item=><div className="asset-analytics-row" key={item.key}><b>{labels[item.key]||item.key}</b><span>{item.incidents||0}</span><span>{item.repeated_incidents||0}</span><span>{item.repairs||0}</span><span>{item.critical_risk_updates||0}</span></div>)}</article>}
