apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticket-service
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatch-service
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asset-service
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
