apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-service-config
  labels:
    app.kubernetes.io/name: dispatch-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  GRPC_PORT: '50058'
  TICKET_SERVICE_ADDR: ticket-service:50052
  BRIGADE_SERVICE_ADDR: brigade-service:50054
  RESERVATION_TTL: 2m
  CLEANUP_INTERVAL: 15s
