apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analytics
  - api-gateway
  - asset
  - audit
  - auth
  - brigade
  - department
  - dispatch
  - file
  - frontend
  - location
  - notification
  - profile
  - report
  - routing
  - sla
  - ticket
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/component in (gateway,backend)
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9464"
          proxy.istio.io/config: '{"holdApplicationUntilProxyStarts":true}'
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          name: metrics
          containerPort: 9464
          protocol: TCP
