---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: automatic-system
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: notification-service
  ports:
  - name: grpc
    port: 50061
    targetPort: 50061
