apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - pgbouncer-connectivity.yaml
images:
  - name: automatic-system-pgbouncer
    newName: ghcr.io/fizzi-77/automatic-system-pgbouncer
    newTag: sha-0000000
