apiVersion: v1
kind: ConfigMap
metadata:
  name: sla-service-config
  labels:
    app.kubernetes.io/name: sla-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  GRPC_PORT: '50060'
  KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
  KAFKA_TICKET_TOPIC: tickets.events.v1
  KAFKA_SLA_TOPIC: sla.events.v1
  KAFKA_CONSUMER_GROUP: sla-service
  DEADLINE_SCAN_INTERVAL: 1s
  LOG_LEVEL: info
