apiVersion: batch/v1
kind: Job
metadata:
  name: migrator-auth
  namespace: automatic-system
  labels:
    app.kubernetes.io/name: migrator-auth
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
    automatic-system.io/job-type: migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrator-auth
        app.kubernetes.io/name: migrator-auth
        app.kubernetes.io/component: job
        app.kubernetes.io/part-of: automatic-system
        app.kubernetes.io/managed-by: kustomize
    spec:
      restartPolicy: Never
      containers:
      - name: migrator
        image: automatic-system/auth-migrator:dev
        imagePullPolicy: IfNotPresent
        env:
        - name: GOOSE_DRIVER
          value: postgres
        - name: GOOSE_DBSTRING
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: AUTH_GOOSE_DBSTRING
        args:
        - -dir
        - /migrations
        - up
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      automountServiceAccountToken: false
      enableServiceLinks: false
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 86400
