services:
  department-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: department
    ports:
      - "50053:50053"
    env_file:
      - .env
    environment:
      KAFKA_BROKERS: host.docker.internal:29092
      GRPC_PORT: "50053"
    depends_on:
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped

  postgres-department:
    image: postgres:16
    container_name: department-postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_department_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${DB_USERNAME}\" -d \"$${DB_NAME}\""]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build: ./migrator
    container_name: department-migrator
    env_file:
      - .env
    depends_on:
      postgres-department:
        condition: service_healthy
    volumes:
      - ./scheme:/migrations
    environment:
      GOOSE_DRIVER: postgres
    command: >
      sh -c 'export GOOSE_DBSTRING="postgres://$${DB_USERNAME}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=$${SSLMODE}";
      goose -dir /migrations up'

volumes:
  postgres_department_data:
