version: "3.9"

services:
  department-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: department
    ports:
      - "50053:50053"
    env_file:
      - .env
    environment:
      GRPC_PORT: "50053"
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: department-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:${DB_PORT}"
    volumes:
      - postgres_department_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build: ./migrator
    container_name: department-migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scheme:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${SSLMODE}
    command: >
      sh -c "
        echo 'Running migrations...' &&
        goose -dir /migrations up
      "

volumes:
  postgres_department_data:
