apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
  labels:
    app.kubernetes.io/name: profile-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
  namespace: automatic-system
data:
  GRPC_PORT: '50055'
  DB_HOST: "postgres-profile"
  DB_READ_HOST: "postgres-profile"
  DB_PORT: '5432'
  DB_USERNAME: "profile_user"
  DB_NAME: "profile_db"
  SSLMODE: "disable"
  AUTH_GRPC_ADDR: "auth-service:50051"
  DEPARTMENT_GRPC_ADDR: "department-service:50053"
  KAFKA_BROKERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
  OUTBOX_WORKER_COUNT: '4'
