auth:
  strategy: anonymous

deployment:
  accessible_namespaces: [automatic-system, istio-system]
  logger:
    log_level: info
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

external_services:
  prometheus:
    url: http://prometheus.automatic-system.svc.cluster.local:9090
  grafana:
    enabled: true
    internal_url: http://grafana.automatic-system.svc.cluster.local:3000/observe/grafana
    external_url: https://fizzi.tail2c9430.ts.net/observe/grafana/
  tracing:
    enabled: true
    internal_url: http://jaeger.automatic-system.svc.cluster.local:16686/observe/jaeger
    external_url: https://fizzi.tail2c9430.ts.net/observe/jaeger/
    use_grpc: false

server:
  web_root: /observe/kiali
