auth:
  strategy: anonymous

deployment:
  accessible_namespaces: [automatic-system, istio-system]
  logger:
    log_level: info
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

external_services:
  prometheus:
    url: http://prometheus.automatic-system.svc.cluster.local:9090
  grafana:
    enabled: true
    internal_url: http://grafana.automatic-system.svc.cluster.local:3000
    external_url: http://localhost:3001
  tracing:
    enabled: true
    internal_url: http://jaeger.automatic-system.svc.cluster.local:16686
    external_url: http://localhost:16686
    use_grpc: false

server:
  web_root: /
