apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automatic-system-observability-auth
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/mesh/observability-auth
  prune: true
  sourceRef:
    kind: GitRepository
    name: automatic-system
  targetNamespace: istio-system
  timeout: 5m
  wait: true
