apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - ../../../base/apps
labels:
  - pairs:
      app.kubernetes.io/environment: local-ha
    includeSelectors: false
patches:
  - path: postgres-ha.patch.yaml
  - path: api-gateway-service.patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=automatic-system
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/sidecar.istio.io~1inject
        value: "true"
images:
  - name: automatic-system/frontend
    newTag: dev
  - name: automatic-system/api-gateway
    newTag: dev
  - name: automatic-system/auth
    newTag: dev
  - name: automatic-system/ticket
    newTag: dev
  - name: automatic-system/department
    newTag: dev
  - name: automatic-system/brigade
    newTag: dev
  - name: automatic-system/profile
    newTag: dev
  - name: automatic-system/location
    newTag: dev
  - name: automatic-system/routing
    newTag: dev
  - name: automatic-system/dispatch
    newTag: dev
  - name: automatic-system/file
    newTag: dev
  - name: automatic-system/sla
    newTag: dev
  - name: automatic-system/notification
    newTag: dev
  - name: automatic-system/audit
    newTag: dev
  - name: automatic-system/analytics
    newTag: dev
  - name: automatic-system/report
    newTag: dev
  - name: automatic-system/asset
    newTag: dev
