apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-location-sentinel
  namespace: automatic-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: redis-location-sentinel
