apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-platform-primary
  namespace: automatic-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
      app.kubernetes.io/instance: platform-primary
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-platform-replicas
  namespace: automatic-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
      app.kubernetes.io/instance: platform-replicas
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-ticket-primary
  namespace: automatic-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
      app.kubernetes.io/instance: ticket-primary
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-ticket-replicas
  namespace: automatic-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
      app.kubernetes.io/instance: ticket-replicas
