-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE notification_preferences(user_id uuid PRIMARY KEY,in_app_enabled bool NOT NULL DEFAULT true,push_enabled bool NOT NULL DEFAULT true,email_enabled bool NOT NULL DEFAULT true,sms_enabled bool NOT NULL DEFAULT false,email text,phone text,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE devices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL,token text NOT NULL UNIQUE,platform text NOT NULL CHECK(platform IN('android','ios','web')),active bool NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX devices_user_idx ON devices(user_id) WHERE active;
CREATE TABLE notification_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_type text NOT NULL,channel text NOT NULL CHECK(channel IN('IN_APP','PUSH','EMAIL','SMS')),subject text NOT NULL DEFAULT '',body text NOT NULL,active bool NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(event_type,channel));
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_id text NOT NULL,user_id uuid NOT NULL,event_type text NOT NULL,title text NOT NULL,body text NOT NULL,data jsonb NOT NULL DEFAULT '{}',read bool NOT NULL DEFAULT false,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(event_id,user_id)); CREATE INDEX notifications_user_idx ON notifications(user_id,created_at DESC);
CREATE TABLE deliveries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),notification_id uuid NOT NULL REFERENCES notifications(id),channel text NOT NULL,recipient text NOT NULL,status text NOT NULL DEFAULT 'PENDING',provider_id text,attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),last_error text,locked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(notification_id,channel,recipient)); CREATE INDEX deliveries_work_idx ON deliveries(status,next_attempt_at);
CREATE TABLE event_inbox(event_id text PRIMARY KEY,event_type text NOT NULL,topic text NOT NULL,payload jsonb NOT NULL,processed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ticket_recipients(ticket_id uuid PRIMARY KEY,user_id uuid,department_id uuid,brigade_id uuid,updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO notification_templates(event_type,channel,subject,body) VALUES
('sla.RESPONSE_WARNING','IN_APP','Срок реакции истекает','По заявке {{ticket_id}} приближается срок реакции'),('sla.RESPONSE_BREACHED','IN_APP','Нарушен SLA реакции','По заявке {{ticket_id}} нарушен срок реакции'),('sla.RESOLUTION_WARNING','IN_APP','Срок выполнения истекает','По заявке {{ticket_id}} приближается срок выполнения'),('sla.RESOLUTION_BREACHED','IN_APP','Нарушен SLA выполнения','По заявке {{ticket_id}} нарушен срок выполнения'),('ticket.assigned','IN_APP','Назначена заявка','Заявка {{ticket_id}} назначена бригаде'),('ticket.completed','IN_APP','Заявка выполнена','Работы по заявке {{ticket_id}} завершены');
-- +goose Down
DROP TABLE ticket_recipients,event_inbox,deliveries,notifications,notification_templates,devices,notification_preferences;
