apiVersion: v1
kind: Namespace
metadata:
  name: automatic-system-dev
  labels:
    app.kubernetes.io/name: automatic-system
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: automatic-system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/environment: dev
