apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - gateway.yaml
  - routes.yaml
  - gateway-public.yaml
  - routes-public.yaml
  - destination-rules.yaml
  - network-policy.yaml
  - public-port-authentication.yaml
