apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
resources:
  - patroni-config.yaml
  - rbac.yaml
  - services.yaml
  - statefulset.yaml
  - backup-cronjob.yaml
  - backup-bucket-job.yaml
  - backup-init-job.yaml
