apiVersion: v1
kind: Service
metadata:
  name: postgres-platform-nodes
  namespace: automatic-system
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    cluster-name: postgres-platform
  ports:
    - name: postgres
      port: 5432
    - name: patroni
      port: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-platform-primary
  namespace: automatic-system
spec:
  selector:
    cluster-name: postgres-platform
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-platform-replicas
  namespace: automatic-system
spec:
  selector:
    cluster-name: postgres-platform
    role: replica
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
