name: Runner Test

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: automatic-system-runner

    steps:
      - uses: actions/checkout@v4

      - name: Check runner
        run: |
          echo "Runner works"
          uname -a