apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automatic-system
secretGenerator:
  - name: runtime-secrets
    envs:
      - runtime.env
generatorOptions:
  disableNameSuffixHash: true
